apiVersion: apps/v1
kind: Deployment
metadata:
  name: payday-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payday-frontend
  template:
    metadata:
      labels:
        app: payday-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: payday-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: payday-frontend
